/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Thomas/Documents/Tang_FPGA_Examples/5.2048/al_ip/chrom.v
 ** Date	:	2018 10 31
 ** TD version	:	4.2.885
\************************************************************/

`timescale 1ns / 1ps

module chrom ( doa, addra, clka, rsta );

	output [31:0] doa;

	input  [9:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_B(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../src/rom_init.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({32{1'b0}}),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule