/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Thomas/Documents/Tang_FPGA_Examples/4.Snake/prj/al_ip/vram.v
 ** Date	:	2018 11 01
 ** TD version	:	4.2.885
\************************************************************/

`timescale 1ns / 1ps

module vram ( 
	dia, addra, clka, rsta, 
	dob, addrb, clkb, rstb
);

	output [3:0] dob;


	input  [3:0] dia;
	input  [8:0] addra;
	input  [8:0] addrb;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(4),
				.DATA_WIDTH_B(4),
				.ADDR_WIDTH_A(9),
				.ADDR_WIDTH_B(9),
				.DATA_DEPTH_A(375),
				.DATA_DEPTH_B(375),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("READBEFOREWRITE"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({4{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule